/**
 * $Id: initMockups.js,v 1.3 2013-01-22 12:03:06 gaudenz Exp $
 * Copyright (c) 2006-2012, JGraph Ltd
 */
var mxMockupC =
{
		BAR_HEIGHT : 'barHeight',
		BAR_POS : 'barPos',
		BG_STYLE : 'bgStyle',
		BG_FLAT_GREEN : 'bgGreen',
		BG_FLAT_WHITE : 'bgWhite',
		BG_FLAT_GRAY : 'bgGray',
		BG_FLAT_CUSTOM : 'bgFlat',
		BG_MAP : 'bgMap',
		BG_STRIPED : 'bgStriped',
		BUTTON_STYLE : 'buttonStyle',
		BUTTON_TEXT : 'buttonText',
		BUTTON_STATE : 'buttonState',
		CHEVRON : 'chevron',
		GRID_SIZE : 'gridSize',
		POINTER_BOTTOM : 'bottom',
		POINTER_POS : 'pointerPos',
		POINTER_TOP : 'top',
		ROUND : 'round',
		SELECTED : '+', 		//has to be one character long
		STATE_ON : 'on',
		STATE_OFF : 'off',
		SUB_TEXT : 'subText',
		
		SHAPE_ACCORDION : 'mockupAccordion',
		SHAPE_BREADCRUMB : 'mockupBreadcrumb',
		SHAPE_BROWSER_WINDOW : 'mockupBrowserWindow',
		SHAPE_BUTTON : 'mockupButton',
		SHAPE_HOR_BUTTON_BAR : 'mockupHorButtonBar',
		SHAPE_HOR_CURLY_BRACE : 'mockupHorCurlyBrace',
		SHAPE_MULTILINE_BUTTON : 'mockupMultilineButton',
		SHAPE_STEP_BAR : 'mockupStepBar',
		SHAPE_VER_BUTTON_BAR : 'mockupVerButtonBar',
		SHAPE_VIDEO_PLAYER : 'mockupVideoPlayer',
		SHAPE_USER_FEMALE : 'mockupUserFemale',
		SHAPE_USER_MALE : 'mockupUserMale',

		SHAPE_IADD_ICON : 'mockupiAddIcon',
		SHAPE_IALERT_BOX : 'mockupiAlertBox',
		SHAPE_IALPHA_LIST : 'mockupiAlphaList',
		SHAPE_IAPP_BAR : 'mockupiAppBar',
		SHAPE_IARROW_ICON : 'mockupiArrowIcon',
		SHAPE_IBG_FLAT : 'mockupiBgFlat',
		SHAPE_IBG_MAP : 'mockupiBgMap',
		SHAPE_IBG_STRIPED : 'mockupiBgStriped',
		SHAPE_IBUTTON : 'mockupiButton',
		SHAPE_IBUTTON_BACK : 'mockupiButtonBack',
		SHAPE_IBUTTON_FORWARD : 'mockupiButtonFw',
		SHAPE_IBUTTON_BAR : 'mockupiButtonBar',
		SHAPE_ICALL_BUTTONS : 'mockupiCallButtons',
		SHAPE_ICALL_DIALOG : 'mockupiCallDialog',
		SHAPE_ICHECKBOX_GROUP : 'mockupiCheckboxGroup',
		SHAPE_ICHECK_ICON : 'mockupiCheckIcon',
		SHAPE_ICLOUD_PROGRESS_BAR : 'mockupiCloudProgressBar',
		SHAPE_ICOMBO_BOX : 'mockupiComboBox',
		SHAPE_ICOPY : 'mockupiCopy',
		SHAPE_ICOPY_AREA : 'mockupiCopyArea',
		SHAPE_IICON_GRID : 'mockupiIconGrid',
		SHAPE_IDELETE_APP : 'mockupiDeleteApp',
		SHAPE_IDELETE_ICON : 'mockupiDeleteIcon',
		SHAPE_IDOWNLOAD_BAR : 'mockupiDownloadBar',
		SHAPE_IDIALOG_BOX : 'mockupiDialogBox',
		SHAPE_IDIRECTION : 'mockupiDir',
		SHAPE_IHOME_PAGE_CONTROL : 'mockupiHomePageControl',
		SHAPE_IKEYB_LETTERS : 'mockupiKeybLett',
		SHAPE_IKEYB_NUMBERS : 'mockupiKeybNumb',
		SHAPE_IKEYB_SYMBOLS : 'mockupiKeybSymb',
		SHAPE_ILOCATION_BAR : 'mockupiLocBar',
		SHAPE_ILOCK_BUTTON : 'mockupiLockButton',
		SHAPE_IHOR_BUTTON_BAR : 'mockupiHorButtonBar',
		SHAPE_IINFO_ICON : 'mockupiInfoIcon',
		SHAPE_ION_OFF_BUTTON : 'mockupiOnOffButton',
		SHAPE_IOPTION : 'mockupiOption',
		SHAPE_IPAGE_CONTROL : 'mockupiPageControl',
		SHAPE_IPAD : 'mockupiPad',
		SHAPE_IPHONE : 'mockupiPhone',
		SHAPE_IPIN : 'mockupiPin',
		SHAPE_IPREV_NEXT : 'mockupiPrevNext',
		SHAPE_IPROGRESS_BAR : 'mockupiProgressBar',
		SHAPE_IRADIO_GROUP : 'mockupiRadioGroup',
		SHAPE_ISLIDER : 'mockupiSlider',
		SHAPE_ISORT_FIND_ICON : 'mockupiSortFindIcon',
		SHAPE_ITEXT_INPUT : 'mockupiTextInput',
		SHAPE_ITOP_BAR : 'mockupiTopBar',
		SHAPE_ITOP_BAR_LOCKED : 'mockupiTopBarLocked',
		SHAPE_IURL_BAR : 'mockupiURLBar',
		SHAPE_IVIDEO_CONTROLS : 'mockupiVideoControls',
		SHAPE_ISCREEN_NAME_BAR: 'mockupiScreenNameBar',
			
		STYLE_FILLCOLOR2 : 'fillColor2',
		STYLE_FILLCOLOR3 : 'fillColor3',
		STYLE_TEXTCOLOR : 'textColor',
		STYLE_TEXTCOLOR2 : 'textColor2',
		STYLE_STROKECOLOR2 : 'strokeColor2',
		STYLE_STROKECOLOR3 : 'strokeColor3'
};